---
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp

- name: debian | adding fluentd repo key
  apt_key:
    url: "{{ fluentd_debian_repo_info.repo_key }}"
    state: present
#    validate_certs: false

- name: debian | adding fluentd repo
  apt_repository:
    repo: "{{ fluentd_debian_repo_info.repo }}"
    state: present

- name: debian | installing fluentd toolbelt
  apt:
    name: "td-agent"
    state: present
    force: yes
