---
# defaults file for ansible-config-interfaces

# Defines if network bonds should be configured as defined
config_network_bonds: false

# Defines if network bridges should be configured as defined
config_network_bridges: false

# Defines if interfaces should be configured as defined
config_network_interfaces: false

# Defines if vlans should be configured as defined
config_network_vlans: false

# Defines all dns servers to configure
dns_nameservers:
  - '8.8.8.8'
  - '8.8.4.4'

# Defines your global dns suffix search
dns_search: '{{ pri_domain_name }}'

# Defines if interfaces, bonds, bridges and vlans should be brought up after defining.
enable_configured_interfaces_after_defining: false

network_bonds: []
  # - name: 'bond0'
  #   address: '192.168.1.10'
  #   netmask: '255.255.255.0'
  #   configure: true
  #   comment: 'Bond Group 0'
  #   method: 'static'
  #   parameters:
  #     - param: 'bond_mode'
  #       val: 'active-backup'
  #     - param: 'bond_miimon'
  #       val: '100'
  #     # - param: 'miimon'
  #     #   val: '100'
  #     # - param: 'mode'
  #     #   val: 'active-backup'
  #     - param: 'primary'
  #       val: 'enp0s9'
  #   slaves:
  #     - 'enp0s9'
  #     - 'enp0s10'

network_bridges: []
  # - name: 'br0'
  #   configure: true
  #   comment: 'Bridge 0'
  #   method: 'static'
  #   address: '192.168.1.11'
  #   netmask: '255.255.255.0'
  #   netmask_cidr: '24'
  #   # gateway: '192.168.1.1'
  #   parameters:
  #     - param: 'bridge_stp'
  #       val: 'off'
  #     - param: 'bridge_fd'
  #       val: '0'
  #     # - param: 'up route add default gw'
  #     #   val: '10.0.106.1'
  #   ports:
  #     - 'enp0s16'

network_interfaces: []
  # - name: 'enp0s3'
  #   configure: true
  #   method: 'dhcp'
  #   parameters:
  #     - param: 'pre-up sleep'
  #       val: '2'
  # - name: 'enp0s8'
  #   configure: true
  #   method: 'static'
  #   address: '192.168.250.10'
  #   netmask: '255.255.255.0'
  # - name: 'enp0s9'
  #   configure: true
  #   comment: 'bond0 member'
  #   method: 'manual'
  #   parameters:
  #     - param: 'bond_master'
  #       val: 'bond0'
  # - name: 'enp0s10'
  #   configure: true
  #   comment: 'bond0 member'
  #   method: 'manual'
  #   parameters:
  #     - param: 'bond_master'
  #       val: 'bond0'
  # - name: 'enp0s16'
  #   configure: true
  #   comment: 'br0 member'
  #   method: 'manual'

network_vlans: []
  # - name: 'enp0s8.100'
  #   configure: true
  #   comment: 'VLAN 100'
  #   method: 'manual'
  #   address:
  #   netmask:
  #   netmask_cidr:
  #   gateway:
  #   vlan_device: 'enp0s8'

pri_domain_name: 'example.org'
