---
# tasks file for ansible-mdadm
#
- include: wipe_disks.yml
  when: >
        mdadm_force_wipe is defined and
        mdadm_force_wipe

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: arrays.yml
