---
# tasks file for ansible-mysql
- include: alpine.yml
  when: ansible_os_family == "Alpine"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: configure_root_access.yml

- include: mysql_check.yml
  when: mysql_config_mysqlchk

- include: setup_replication.yml
  when: mysql_config_replication
