---
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'apt-transport-https'
    - 'pwgen'

- name: debian | Installing Default Java JRE
  apt:
    name: "default-jre-headless"
    state: "present"
  when: graylog_install_default_java_jre

- name: debian | installing graylog repo
  apt:
    deb: "{{ graylog_debian_package_info.url }}/{{ graylog_debian_package_info.file }}"
    state: "present"
    # dpkg_options: "force-all"
  register: "graylog_repo"

- name: debian | updating apt-cache
  apt:
    update_cache: yes
  when: graylog_repo.changed

- name: debian | installing graylog
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - graylog-server
#    - graylog-web
