---
- name: redhat | Setting Up EPEL
  yum:
    name: "epel-release"
    state: "present"
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'pwgen'
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'java-1.8.0-openjdk-headless'
  when: >
        ansible_distribution != "Fedora" and
        graylog_install_default_java_jre

- name: redhat | Installing Graylog Repo
  yum:
    name: "{{ graylog_redhat_package_info.url }}/{{ graylog_redhat_package_info.file }}"
    state: "present"
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Graylog Server
  yum:
    name: "graylog-server"
    state: "present"
  when: ansible_distribution != "Fedora"
