---
- name: debian | Installing Pre-Reqs for Ubuntu Precise and Older
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'python-software-properties'
  when: ansible_distribution_version|int < 14

- name: debian | Adding Jenkins Repo Key
  apt_key:
    url: "{{ jenkins_repo_key }}"
    state: "present"

- name: debian | Adding Jenkins Repo
  apt_repository:
    repo: "{{ jenkins_apt_repo }}"
    state: "present"

- name: debian | Installing Jenkins Pre-Reqs
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: '{{ jenkins_debian_pre_req_packages }}'

- name: debian | Installing Jenkins
  apt:
    name: "jenkins"
    state: "present"
